version: "3.8"

services:
  ol-assistant:
    build:
      context: https://github.com/Tahl0s/jigsaw-unified-deployment-engine.git
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: main-app-flask.py
      FLASK_ENV: production
      OLLAMA_HOST: ollama         # Environment variable to connect to ollama container
      OLLAMA_PORT: 5001           # Port Ollama is exposed on
    volumes:
      - .:/appa
      - ./data:/app/data
      - ./memory:/memory
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - jigsaw-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - ol-assistant
    restart: unless-stopped
    networks:
      - jigsaw-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "5001:5001"  # Ensure Ollama runs on the right port
    restart: unless-stopped
    networks:
      - jigsaw-network

networks:
  jigsaw-network:
    driver: bridge
