version: "3.8"

services:
  ol-assistant:
    build:
      context: .
      dockerfile: Dockerfile  # Ensure this points to the updated Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: main-app-flask.py
      FLASK_ENV: production
    volumes:
      - .:/app  # Mounts the project directory (optional, only if you need local changes to reflect)
      - ./data:/app/data  # Persists data/logs
    restart: unless-stopped  # Ensures auto-restart on failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - ol-assistant
    restart: unless-stopped
